version: '3.8'
services:
  barber_db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./app.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - barber_app
  barber_api:
    container_name: barber_api
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - barber_volumes:/usr/src/app/
    depends_on:
      - barber_db
    networks:
      - barber_app

volumes:
  pgdata:
  barber_volumes:

networks:
  barber_app:
    driver: bridge
